---
- name: Configure Ethernet interface (eth0) for Internet Sharing (DHCP client)
  community.general.nmcli:
    type: ethernet
    conn_name: "DirectEthernet"
    ifname: "eth0"
    state: up
    autoconnect: true
    method4: auto
  become: true

- name: Install dnsmasq for isolated DHCP
  ansible.builtin.apt:
    name: dnsmasq
    state: present
  become: true

- name: Configure dnsmasq for AP without gateway/DNS
  ansible.builtin.template:
    src: bebecam_ap.conf.j2
    dest: /etc/dnsmasq.d/bebecam_ap.conf
    mode: "0644"
    owner: root
    group: root
  become: true
  notify: Restart dnsmasq

- name: Ensure dnsmasq is enabled
  ansible.builtin.systemd:
    name: dnsmasq
    enabled: true
    state: started
  become: true

- name: Configure Wi-Fi Hotspot (AP)
  community.general.nmcli:
    type: wifi
    conn_name: "{{ ap_ssid }}"
    ifname: "{{ wifi_interface }}"
    ssid: "{{ ap_ssid }}"
    state: up
    autoconnect: true
    ip4: "{{ ap_ip_addr }}"
    method4: manual
    wifi:
      mode: ap
      band: bg
      channel: 6
    wifi_sec:
      key-mgmt: wpa-psk
      psk: "{{ ap_password }}"
  become: true
